services:
  authenticationservice:
    build:
      context: ./AuthenticationService  # 👈 ændret
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__Default=server=usersdb;user=root;password=root;database=usersdb
      - Jwt__Secret=LuckyNumberFoxtrot
    depends_on:
      - usersdb
    networks:
      - foxtrot
    ports:
      - "8081:5000"

  usersdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usersdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - foxtrot

networks:
  foxtrot:
    external: true
